"""create readings table

Revision ID: 8edbaf95c9bb
Revises: 
Create Date: 2026-10-05 07:50:32.458089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8edbaf95c9bb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('readings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('temperature_c', sa.Float(), nullable=False),
    sa.Column('humidity', sa.Integer(), nullable=False),
    sa.Column('wind_kmh', sa.Float(), nullable=False),
    sa.Column('condition', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_readings_city'), 'readings', ['city'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_readings_city'), table_name='readings')
    op.drop_table('readings')
    # ### end Alembic commands ###
